### ISSUE TITLE
Intune Tools - ADMX Ingestion error in Import

### ISSUE THREAD

**Issue by HornEman71** [Micke-K/IntuneManagement#38] opened 2022-01-17 12:15 UTC
Hi, loving the new features and thought would give it a go with an ADMX import policy.  Anything to save time is brilliant!

I have loaded inetres.admx (no adml) file and tried enabling the top 7 settings within $(string.InternetCPL) to block Internet Options in Control Panel e.g. Advanced Tab down to Restrict Security Tab.

When clicking on import and checking the log files I get this error

Failed to invoke MS Graph with URL https://graph.microsoft.com/BETA/deviceManagement/deviceConfigurations (Request ID: 1ebf6dec-b3a4-4ed8-9185-dcedc6a4dd4b). Status code: BadRequest

Have Microsoft changed the api or are additional security permissions required etc?  Many thanks for any help!

Justin

**Comment by HornEman71** [comment] 2022-01-17 12:27
Hi quick follow up - I removed the tick for Ingest ADMX file and it imported.

**Comment by Micke-K** [comment] 2022-01-20 01:36
Hello!

Sorry for late answer. I've been down sick.

My guess is that the ADMX file contains unsupported reg paths. Microsoft does not allow you to specify policy settings under System, Software\Microsoft, and Software\Policies\Microsoft with some exceptions. 

Have a look at the documentation here: https://docs.microsoft.com/en-us/windows/client-management/mdm/win32-and-centennial-app-policy-configuration

Cheers!

**Comment by Micke-K** [comment] 2022-04-26 11:53
Closing this issue since this is expected behaviour with ADMX files that has unsupported.

**Closed as completed by Micke-K** 2022-04-26 11:53 UTC
