### ISSUE TITLE
Importing assignment "All devices - Filters"

### ISSUE THREAD

**Issue by royklo** [Micke-K/IntuneManagement#178] opened 2023-12-05 11:54 UTC
When I exported a setting catalog policy from my staging tenant and imported it to my test tenant. I noticed that it doesn't adds the correct filter on it. 

Below I added a screenshot. As you can see, it will show "No access".  But the windows 11 filter is there.

![image](https://github.com/Micke-K/IntuneManagement/assets/76492458/4660c1d5-19f0-404a-b30d-99bd49a9a395)
![image](https://github.com/Micke-K/IntuneManagement/assets/76492458/b36e22c7-5732-4958-b70a-8876c1aa1bea)

**Comment by Micke-K** [comment] 2023-12-10 10:33
Hello,

This is by the current design. Update will only update settings and not the Assignment. With replace, it will copy the assignments of the old object over to the new. This was me being carful when updating policies or moving them between environments.. I'm never comfortable when importing policies + assignments. Especially when All Users or All Devices is used.

I might revisit this design though in the future if there is a request for it. I don't know how many actually import policies with assignments and also would need a functionality like this where the actual assignments are updated.

Cheers!

**Comment by Micke-K** [comment] 2024-01-02 07:22
Closing this as by design. I will have it in mind during future development.

**Closed by Micke-K** 2024-01-02 07:22 UTC
