### ISSUE TITLE
Documentation related functions cause an exception when calling "Parse" on machines with date format dd/mm/yyyy.

### ISSUE THREAD

**Issue by illuvtar** [Micke-K/IntuneManagement#44] opened 2022-03-07 04:45 UTC
Documentation related functions cause an exception when calling "Parse" on machines with date format dd/mm/yyyy.
_or month and day are swapped if day value 12 or below_

Error:
> Get documentation info for Prod_Win_WindowsUpdates_Broad (Update Policies)
> MethodInvocationException: Exception calling "Parse" with "1" argument(s): "String '02/15/2022 01:50:53' was not recognized as a valid DateTime."
> InvalidOperation: You cannot call a method on a null-valued expression.
> InvalidOperation: You cannot call a method on a null-valued expression.

Code: [Documentation.psm1](https://github.com/Micke-K/IntuneManagement/blob/46435b5717f27001639a7cdea2408a4598cef24c/Extensions/Documentation.psm1#L590)

**Comment by Micke-K** [comment] 2022-03-07 07:04
Hello!

I cannot reproduce this even if I change my date/time format.

createdDateTime, lastModifiedDateTime and modifiedDateTime should be stored in the "2021-08-10T04:42:10.4104838Z" format. I cannot find any object that stores it in '02/15/2022 01:50:53' format as the error states.

How does it look in the detail view? Can you attach the policy that you are trying to document?

Cheers!

**Comment by illuvtar** [comment] 2022-03-07 08:10
I was able to replicate this in a Windows Sandbox using the following:

1. Get current culture information (sandbox returned en-US for me)
```
Get-Culture
#LCID             Name             DisplayName
#----             ----             -----------
#1033             en-US            English (United States)
```

2. Set culture info to en-NZ (any country with dd/mm/yyyy date format will work)
```
Set-Culture -CultureInfo en-NZ
```
3. Restart powershell
4. Run .\Start-IntuneManagement.ps1 -ShowConsoleWindow
5. Document attached json or any config with day created/lastmodified on the 13th or above and check console for Parse errors

I was able to work around the issue with ([DateTime]::Parse(([datetime]$obj.createdDateTime).ToString((get-culture))))

[Prod_iOS_Compliance.zip](https://github.com/Micke-K/IntuneManagement/files/8195770/Prod_iOS_Compliance.zip)

Hope this helps replicate the issue.

Thanks

**Comment by Micke-K** [comment] 2022-03-07 09:09
I cannot reproduce it no matter what I do.

Can you try this file
[Documentation.zip](https://github.com/Micke-K/IntuneManagement/files/8196322/Documentation.zip)
?

**Comment by microsoftems** [comment] 2022-03-07 11:47
Similar errors in the console:
```
Loading Prod_iOS_Compliance
Get documentation info for Prod_iOS_Compliance (Compliance Policies)
WARNING: Failed to parse date from string 02/15/2022 03:51:28
WARNING: Failed to parse date from string 02/15/2022 03:51:28
```

Resulting documents now contain Created and Last modified date/time in the format mm/dd/yyyy hh:mm:ss
![image](https://user-images.githubusercontent.com/63212526/157024143-0aef8e81-8a52-43d8-a0e8-b9a4358ce96b.png)

**Comment by Micke-K** [comment] 2022-03-07 12:12
That is with the updated psm1. I did a try/catch statement and logged if it failed to parse. I still can understand why the date/time format is completely different from what I get from Graph. Unless something has changed or is different based on where the tenant is. 

I found this link where it suggests that it might be a bug somewhere. In .NET?

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/79

**Comment by Micke-K** [comment] 2022-03-07 12:57
Can you try this and let me know what it says in the log. Just some more logging

[Documentation.zip](https://github.com/Micke-K/IntuneManagement/files/8197830/Documentation.zip)
 
Cheers!

**Comment by martincaddick** [comment] 2022-03-10 22:01
Where is the tenant? In the past I've seen different issues depending on where the tenant is. We're a bit different down under ;-)

**Comment by Micke-K** [comment] 2022-03-10 22:10
My tenant us in Australia. I live in Sydney and I do know things are a bit different here :). I used to live in Sweden so I know regional settings can be a big issue. Date conversations has been a problem for a long time. 

I still can"t figure out why it returns a different date format for you. I wonder where that happens. If use the same query in Graph Explorer, what do you get then?

**Comment by Micke-K** [comment] 2022-03-17 20:41
Hello!

Looks like this is a PowerShell 6+ issue. 

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-json?view=powershell-7.2#notes

Try starting the script with PowerShell 5 eg add -version 5 to the command line.

**Comment by Micke-K** [comment] 2022-04-26 11:52
Try the new version. It uses -version 5 in the cmd files. Which should force it back to version 5 behaviour.

Let me know how it goes

**Comment by Micke-K** [comment] 2022-09-10 05:39
Closing this. This happens when using PowerShell 6+. Cmd files will always user PowerShell 5.

**Closed** 2022-09-10 05:39 UTC
