### ISSUE TITLE
Copy application not working

### ISSUE THREAD

**Issue by ncheymol** [Micke-K/IntuneManagement#42] opened 2022-02-24 14:35 UTC
the functionality to copy application doesn't download and upload the app content. 

The application created is unusable : 
Your app is not ready yet. If app content is uploading, wait for it to finish. If app content is not uploading, try creating the app again.

**Comment by Micke-K** [comment] 2022-02-25 09:30
Hello!

That is by design at the moment. The core thing here is that Microsoft does not allow to export content. So copy will not work. 

I'll have a look and see if I can do the same as for import. It would then upload the file if it is found locally. 

Cheers!

**Comment by ncheymol** [comment] 2022-02-25 11:27
If you can add a popup to go select the file or the folder locally it would be a good work around

**Comment by Micke-K** [comment] 2022-03-03 11:29
This is fixed in the latest update. 

Please test and see if it works the way you expect it to. 

Cheers!

**Comment by ncheymol** [comment] 2022-03-07 13:11
It's working, thanks

**Closed** 2022-03-08 08:23 UTC
