### ISSUE TITLE
Document button is grey when initially selecting all

### ISSUE THREAD

**Issue by martincaddick** [Micke-K/IntuneManagement#36] opened 2021-11-15 07:17 UTC
Hopefully an easy one. If I select the tickbox at the top and hence select all items, the Document button stays greyed out. Work around is to select one of the individual items and then select the top tickbox. Document button then behaves as expected.

![image](https://user-images.githubusercontent.com/73564857/141738140-21bc4743-6cb6-4a69-99e2-d8733d9f35c2.png)

**Comment by Micke-K** [comment] 2021-11-15 08:03
This is caused by a bad design. The buttons are enabled/disabled by the selecteditem changed event. That is never triggered when a checkbox is selected/unselected. I'll see if I can look into as well. 

Cheers!

**Comment by Micke-K** [comment] 2022-03-03 11:35
This is now fixed. Can I lose this?

Cheers!

**Comment by martincaddick** [comment] 2022-03-03 20:38
Yes fixed. Close please.

**Closed** 2022-03-03 20:39 UTC
