### ISSUE TITLE
Issue comparing assignments

### ISSUE THREAD

**Issue by Influencer101** [Micke-K/IntuneManagement#274] opened 2024-10-07 21:31 UTC
Hi Micke-K,

Hope all is well and you still find the time and motivation to continue to improve this great tool! 

When trying to compare two policies, we find the assignments (assigned group) are not compared properly. Instead of showing a single row, the assigned groups are shown on 2 different rows and instead of the name of the group the object id is shown, see the attached screen shot. Can you please look into this and let us know if this can be fixed. Thanks in advance!

![Compare assignments](https://github.com/user-attachments/assets/5ed198de-1076-475b-b475-c4d6bd67fd79)

**Comment by Micke-K** [comment] 2024-10-07 22:41
Hello,

I'm still working on it. I've been crazy busy lately so I haven't had as much time I would like for it. 

Are these comparing between two environments? Guid normally means that the group is deleted or group info is not available for exported policy. 

Cheers!

**Comment by Influencer101** [comment] 2024-10-08 12:46
Hi Micke-K,

Thanks for your quick reply. It's indeed a compare of policies from different tenants.  The groups are still there and assigned. 

I noticed when I document a policy the group assignements is also not exported to the CSV.

**Comment by Micke-K** [comment] 2024-10-12 02:05
Hello,

I just released 3.9.8. This should fix both the Group name on exported policies during compare and group name in CSV output.

Not that the Assignments will have multiple lines if they don't match. This is by design. If the group names are the same, it will be a single line. 

Cheers!

**Comment by Influencer101** [comment] 2024-10-13 16:48
Hi Micke-K,

Fantastic! Thanks a lot for fixing this on such a short notice. 

Cheers!

**Comment by Micke-K** [comment] 2024-12-08 07:26
Closing issue. Included in 3.9.8

**Closed by Micke-K** 2024-12-08 07:26 UTC
