### ISSUE TITLE
App Protection Object Issue

### ISSUE THREAD

**Issue by jsny-7** [Micke-K/IntuneManagement#15] opened 2021-05-25 21:00 UTC
It looks like there may be a issue with the when trying to load App Protection objects it gives the following error: 

Cannot find an overload for "new" and the argument count: "1".

**Comment by Micke-K** [comment] 2021-05-25 22:33
"...load App Protection objects..." - Do you mean Import them, use "Load full" in detailed view or loading all of them?
I could not reproduce this error with the App Protection policies I have.
What type of App Protection policy is it?

**Comment by DanielBoule** [comment] 2021-07-09 12:24
I have the same issue, the error occur when we select App protection in the menu. No app protection are list. 

Loading App Protection objects
Cannot find an overload for "new" and the argument count: "1".
At D:\Intune\IntuneManagement-master\Extensions\MSGraph.psm1:384 char:5
+     $ocList = [System.Collections.ObjectModel.ObservableCollection[ob ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

**Comment by Micke-K** [comment] 2021-07-09 12:31
Thank you for the update. That really helps troubleshooting. I might have an idea what it could be. I'll have a look at this on the weekend.

**Comment by Micke-K** [comment] 2021-07-10 08:01
I found the bug. This will be fixed in the next release. This will happen if there is only one App Protection policy.
Workaround for now: Create a Dummy app protection to list the objects....

**Comment by Micke-K** [comment] 2021-07-12 10:26
Fix uploaded. Please test and let me know how it goes

**Comment by DanielBoule** [comment] 2021-07-12 10:49
Thank you , i will test it today

Daniel Boulé
514-452-6458

________________________________

**Comment by DanielBoule** [comment] 2021-07-12 12:17
Everything work , thank you.


Daniel Boulé


________________________________
De : Mikael Karlsson ***@***.***>
Envoyé : 10 juillet 2021 04:01
À : Micke-K/IntuneManagement ***@***.***>
Cc : DanielBoule ***@***.***>; Comment ***@***.***>
Objet : Re: [Micke-K/IntuneManagement] App Protection Object Issue (#15)


I found the bug. This will be fixed in the next release. This will happen if there is only one App Protection policy.
Workaround for now: Create a Dummy app protection to list the objects....

**Closed** 2021-07-12 21:41 UTC
Labels: bug
