### ISSUE TITLE
Policies for Office Apps Missing

### ISSUE THREAD

**Issue by jpkool** [Micke-K/IntuneManagement#198] opened 2024-02-09 16:32 UTC
There is no ability to export the "Policies for Office apps" that are created on the tenant. Also missing in the GUI.

**Comment by Micke-K** [comment] 2024-02-09 23:14
Hello

This is by design. Office policies are not in Graph. That are managed by Office APIs. 

I'll have a look if they've changed it. 

Cheers!

**Comment by Micke-K** [comment] 2024-12-08 07:47
Closing this since it is not supported.

**Closed by Micke-K** 2024-12-08 07:47 UTC
